### PR TITLE
Fix docker-hatch permission failure

### PR DESCRIPTION
**Pull request by rosbo**
The error is:

```
error checking context: no permission to read from
```

Thread: https://chat.kaggle.net/kaggle/pl/5zbr1udo1by49jetq15uho7ffe

### CODE REVIEW

**Comment by rosbo** [comment]
I can't repro the issue. @goeffthomas Can you pull the branch and test and let me know?

**Comment by goeffthomas** [comment]
> Can you pull the branch and test and let me know?

On this branch, the `chmod` changes to the files aren't present, so I now get other/different context errors. This time:
`error checking context: no permission to read from '/usr/local/google/home/goeff/git/kagglehub/src/kagglehub/__pycache__/__init__.cpython-311.pyc'`

**Comment by rosbo** [comment]
Added the `__pycache__` folders and tested in a GVC with Goeff.

**Review by goeffthomas — APPROVED** [review]
Thank you!!

**Pull request merged**
